name: Remote Terminal Session
on: workflow_dispatch

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH server
        run: |
          sudo apt update
          sudo apt install -y openssh-server
          sudo service ssh start
          echo "runner:${{ secrets.userpassword }}" | sudo chpasswd

      - name: Install cloudflared
        run: |
         wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
         sudo dpkg -i cloudflared-linux-amd64.deb

      - name: Start Cloudflare Quick Tunnel
        run: |
          cloudflared tunnel --url ssh://localhost:22
